### ISSUE TITLE
Problems with the yarpmanager applications

### ISSUE THREAD

**Issue by S-Dafarra** [vvv-school/tutorial_impedance-control#5]
While testing this tutorial for the ``icub-training`` course, I had some issues with the yarpmanager applications. In particular ``iCubGazeboV2_5`` was specified as the robot to be used (see [here](https://github.com/vvv-school/tutorial_impedance-control/blob/2772259474e390ea592a0ea9b0b18419b8c0a69c/app/scripts/tutorial_impedance-control-app.xml#L16)). The problem is that the world loaded by the [other application](https://github.com/vvv-school/tutorial_impedance-control/blob/2772259474/app/scripts/tutorial_impedance-control-system.xml#L13) loads the ``iCubGazeboV2_5`` model, as specified [here](https://github.com/robotology/icub-gazebo-wholebody/blob/master/worlds/icub_simple_fixed_world/icub_simple_fixed.world#L23). So I recently modified it to use the ``icubGazeboSim`` with this commit: https://github.com/vvv-school/tutorial_impedance-control/commit/8240ceaf649f943312f1de67712ac3f18e3bc0a2.
The problem then, was that the ``model.urdf`` of ``icubgazeboSim`` was not installed with ``icub-models``. In order to have it, we would need to install [``yarp-wholebodyinterface``](https://github.com/robotology/yarp-wholebodyinterface/tree/master/app/robots), but in turns it needs [``wholebodyinterface``](https://github.com/robotology/wholebodyinterface). All together they are a bit too long list of dependencies to run this tutorial. Thus I would see the following solutions:
- Add the ``model.urdf`` of ``icubGazeboSim`` in this repo.
- Add the ``model.urdf`` of ``icubGazeboSim`` in ``icub-models``.
- Change the world of ``icub-gazebo-wholebody`` to use the ``iCubGazeboV2_5`` model.
- Use the ``robotology-superbuild`` to install all the repos, thus changing the [installation instructions](https://github.com/icub-training/icub-training.github.io/wiki/Installation)

P.s. By following the installation instructions above, no one was able to make the world file working.

**Comment by pattacini** [comment]
Let me just add the point that I warned you that the instructions above might have been incomplete and thus needed a double check for the use of a tutorial that wasn't under my responsibility 😉 

That said, I can be in favor of using the superbuild next time (for core components only).

**Comment by S-Dafarra** [comment]
> Let me just add the point that I warned you that the instructions above might have been incomplete and thus needed a double check for the use of a tutorial that wasn't under my responsibility

I am not blaming anyone. It was my duty to check it beforehand. I did not test it in a clean installation and I missed the fact that ``icubGazeboSim`` ``urdf`` is not installed by any of the repo in the instructions. One of the nice thing of using the superbuild is that you don't need to remember from which repo a specific file is coming from :grimacing: .

**Comment by pattacini** [comment]
What about @S-Dafarra for the time being fixing this issue by pursuing option 1 or 2?
